# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webhookdb < Formula
  desc "Query and store any API in real-time with SQL. More at https://webhookdb.com"
  homepage "https://webhookdb.com"
  version "0.15.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webhookdb/webhookdb-cli/releases/download/0.15.0/webhookdb_0.15.0_macos_x86_64.tar.gz"
      sha256 "3b15eac6b9cb47ffa9037e36e5ca4f4eb696a49a2f9716e03f5c231271378a2a"

      def install
        bin.install "webhookdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webhookdb/webhookdb-cli/releases/download/0.15.0/webhookdb_0.15.0_macos_arm64.tar.gz"
      sha256 "d2d77f58224f53a96321879c20b015e21db7cfca04168af67c8ce7baa0b0dec8"

      def install
        bin.install "webhookdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/webhookdb/webhookdb-cli/releases/download/0.15.0/webhookdb_0.15.0_linux_x86_64.tar.gz"
      sha256 "54d43e34d2a6e57d0f02705f50923902415160b05d44afdfc8d32ce944fb000f"

      def install
        bin.install "webhookdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webhookdb/webhookdb-cli/releases/download/0.15.0/webhookdb_0.15.0_linux_arm64.tar.gz"
      sha256 "ceea1ae561949c05701361fe7226f00fdd024a7eda3f1154eca6a477fdf28a27"

      def install
        bin.install "webhookdb"
      end
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the WebhookDB CLI! Run `webhookdb auth login` to get register or sign in.
    EOS
  end
end
