# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webhookdb < Formula
  desc "WebhookDB queries any API in real-time with SQL. More at https://webhookdb.com"
  homepage "https://webhookdb.com"
  version "0.9.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lithictech/webhookdb-cli/releases/download/0.9.1/webhookdb_0.9.1_macos_x86_64.tar.gz"
      sha256 "950c9687ba89aece129be57ca6484a8174a689d0a24d2ebd70212162811c0c23"

      def install
        bin.install "webhookdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lithictech/webhookdb-cli/releases/download/0.9.1/webhookdb_0.9.1_macos_arm64.tar.gz"
      sha256 "a69eb42c669429bdb05f2c66d6fb97aac852586b838a27ba1c9dddb76f16fb93"

      def install
        bin.install "webhookdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lithictech/webhookdb-cli/releases/download/0.9.1/webhookdb_0.9.1_linux_arm64.tar.gz"
      sha256 "2e69e76e672aeefb98aff0e40655774f6df52ee92fbdc39c6074d82e3756c322"

      def install
        bin.install "webhookdb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lithictech/webhookdb-cli/releases/download/0.9.1/webhookdb_0.9.1_linux_x86_64.tar.gz"
      sha256 "0dea6f7f5b9c74d8568a2eb4ea1ab49fc7080aa3dd0c7aca1ecd652aea7df0ab"

      def install
        bin.install "webhookdb"
      end
    end
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the WebhookDB CLI! Run `webhookdb auth login` to get register or sign in.
  EOS
  end
end
