# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webhookdb < Formula
  desc "Query and store any API in real-time with SQL. More at https://webhookdb.com"
  homepage "https://webhookdb.com"
  version "0.9.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lithictech/webhookdb-cli/releases/download/0.9.2/webhookdb_0.9.2_macos_arm64.tar.gz"
      sha256 "9cb6b93c93c4bd621602cb70da89d401e0828180e7866587f8bc03391b8afd71"

      def install
        bin.install "webhookdb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lithictech/webhookdb-cli/releases/download/0.9.2/webhookdb_0.9.2_macos_x86_64.tar.gz"
      sha256 "3f6aeefb014e4a3b4cf5fcbc45998ddfccb19ad8adbbf6b5ddcd630aea4bb5f2"

      def install
        bin.install "webhookdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lithictech/webhookdb-cli/releases/download/0.9.2/webhookdb_0.9.2_linux_arm64.tar.gz"
      sha256 "b8002e75460b825a7df1058729b148199c401d3dff471745e534838ba036cb65"

      def install
        bin.install "webhookdb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lithictech/webhookdb-cli/releases/download/0.9.2/webhookdb_0.9.2_linux_x86_64.tar.gz"
      sha256 "de313ac0c25b8089eda90c05279ec2a3546f4dc33a502515dea17642ae829b7f"

      def install
        bin.install "webhookdb"
      end
    end
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the WebhookDB CLI! Run `webhookdb auth login` to get register or sign in.
  EOS
  end
end
