# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebhookdbCli < Formula
  desc "Use WebhookDB to query any API, in real-time, with SQL. More at https://webhookdb.com"
  homepage "https://webhookdb.com"
  version "0.3.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lithictech/webhookdb-cli/releases/download/0.3.8/webhookdb-cli_0.3.8_macos_arm64.tar.gz"
      sha256 "056b7cd9f5f09fb97805e9c1a145cf2741a8de0279ffe505415a9c440d60c439"

      def install
        bin.install "webhookdb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lithictech/webhookdb-cli/releases/download/0.3.8/webhookdb-cli_0.3.8_macos_x86_64.tar.gz"
      sha256 "28d3f9e7fc650c0b737aa4593a60d97430012c30ce09d8f0044b545770de639a"

      def install
        bin.install "webhookdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lithictech/webhookdb-cli/releases/download/0.3.8/webhookdb-cli_0.3.8_linux_arm64.tar.gz"
      sha256 "f0f6a3d9cee3075c1bb97cde5edafd2034267040ca299e68a7efdc54eb0a97d5"

      def install
        bin.install "webhookdb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lithictech/webhookdb-cli/releases/download/0.3.8/webhookdb-cli_0.3.8_linux_x86_64.tar.gz"
      sha256 "f0452a1a24e452a20a313f4abd9316fb3aaf243999139dc9e6ff35f4e5fda25b"

      def install
        bin.install "webhookdb"
      end
    end
  end
end
